import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/redux/ReduxProvider";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/toaster";
import { GoogleTagManager } from "@next/third-parties/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Welcome - Developer Eman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const environment = process.env.NODE_ENV === "production" ? true : false;
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ReduxProvider>
            <NextTopLoader />
            {environment && <GoogleTagManager gtmId="G-3BRTFCYKXQ" />}
            <SpeedInsights />
            {children}
            <Toaster />
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
